import { Config } from "./types";

export const StandardConfig: Config = {
    cards: 53,
    epidemics: 6,
    cities: {
        Algiers: 1,
        Atlanta: 1,
        Baghdad: 1,
        Bangkok: 1,
        Beijing: 1,
        Bogota: 1,
        "Buenos Aires": 1,
        Cairo: 1,
        Calcutta: 1,
        Chennai: 1,
        Chicago: 1,
        Delhi: 1,
        Essex: 1,
        "Ho Chi Minh City": 1,
        "Hong Kong": 1,
        Istanbul: 1,
        Jakarta: 1,
        Johannesburg: 1,
        Karachi: 1,
        Khartoum: 1,
        Kinshasa: 1,
        Lagos: 1,
        Lima: 1,
        London: 1,
        "Los Angeles": 1,
        Madrid: 1,
        Manila: 1,
        "Mexico City": 1,
        Miami: 1,
        Milan: 1,
        Moscow: 1,
        Mumbai: 1,
        "New York": 1,
        Osaka: 1,
        Paris: 1,
        Riyadh: 1,
        "San Francisco": 1,
        Santiago: 1,
        "Sao Paulo": 1,
        Seoul: 1,
        Shanghai: 1,
        "St. Petersburg": 1,
        Sydney: 1,
        Taipei: 1,
        Tehran: 1,
        Tokyo: 1,
        Toronto: 1,
        Washington: 1,
    },
};
